"""[summary]

    This file provides several functions that creates the
    command line compiler calls, generated after parsing the
    Zork config file and retrieve the data
"""

import glob
import os
import subprocess

from program_definitions import CLANG, GCC, MSVC
from utils.exceptions import LanguageLevelNotEnought, UnsupportedCompiler


def build_project(config: dict, verbose: bool, project_name: str) -> int:
    """ Calls the selected compiler to perform the build of the project """

    generate_build_output_directory(config)

    compiler = config['compiler'].cpp_compiler
    command_line: list = []

    if compiler == CLANG:
        command_line = call_clang_to_compile(config, verbose, project_name)
    elif compiler == GCC:
        raise UnsupportedCompiler(GCC)
    else:
        raise UnsupportedCompiler(MSVC)

    if verbose:
        print(f'Command line to execute: {" ".join(command_line)}\n')

    return subprocess.Popen(command_line).wait()


def call_clang_to_compile(config: dict, verbose: bool, project_name: str):
    """ Calls Clang++ to compile the provide files / project """
    # Generates the compiler and linker calls
    command_line = [
        config.get('compiler').cpp_compiler,
        '--std=c++' + config.get('language').cpp_standard,
        '-stdlib=' + config.get('language').std_lib,
        '-o', config['build'].output_dir + '/' +
        config.get("executable").executable_name
        .replace(
            '<autogenerated_executable>',
            project_name
        )
    ]

    for source in config.get("executable").sources:
        command_line.append(source)

    # Generates a compiler call to prebuild the module units, in case that
    # the attribute it's present, have a valid path to the .cppm module units
    # and the language level it's at least, c++20.
    if config['language'].modules == 'true':
        if int(config.get('language').cpp_standard) < 20:
            raise LanguageLevelNotEnought(
                20,
                config.get('language').cpp_standard,
                "Modules"
            )

        # TODO Modulos en Clang requieren de extensión .cppm
        prebuild_modules_path, interfaces = _clang_prebuild_module_interfaces(
            config, verbose, project_name
        )
        _compile_module_implementations(config, verbose, project_name)

        for module_ifc in config['modules'].interfaces:
            command_line.append(module_ifc)
        for module_src in config['modules'].implementations:
            command_line.append(module_src)

        command_line.append('-fmodules')
        command_line.append(
            f'-fprebuilt-module-path={prebuild_modules_path}'
        )

    return command_line


def _clang_prebuild_module_interfaces(
    config: dict,
    verbose: bool,
    project_name: str
) -> list:
    """ The responsable for generate de module units
        for the C++20 modules feature.
        Returns a list with the args that should be passed into them
        main compiler call in order to enable the modules compilation
        and linkage """
    output_dir: str = config['build'].output_dir
    modules_dir_path = output_dir + '/modules'
    module_ifcs_dir_path = modules_dir_path + '/interfaces'

    if verbose:
        print('Precompiling the module interfaces...')
    # Generate the precompiled modules directory if it doesn't exists
    if 'modules' not in os.listdir(output_dir):
        subprocess.Popen(['mkdir', modules_dir_path]).wait()
        subprocess.Popen(['mkdir', module_ifcs_dir_path]).wait()

    mods_from_config: list = config.get('modules').interfaces
    module_ifcs: list = [] if len(mods_from_config) == 1 \
        else mods_from_config

    ifcs_path = f'./{project_name}/include/{project_name}/*.cppm'
    if len(mods_from_config) == 1:
        for wildcarded_source in glob.glob(ifcs_path):
            module_ifcs.append(wildcarded_source.replace('\\', '/'))

    print(f'MODULE INTERFACES: {module_ifcs}')

    for module in module_ifcs:
        # Strips the path part if the module name it's inside a path,
        # (like 'src/inner/module_file_name.cppm') and not alone,
        # as a *.cppm file. Also, strips the file extension for
        # replace it the file name ext for the .pcm one
        if module.__contains__('/'):
            module_dir_parts_no_slashes: list = module.split('/')
            module_name: str = \
                module_dir_parts_no_slashes[
                    len(module_dir_parts_no_slashes) - 1
                ]
            module_name_no_extensions = ''.join(module_name.split('.')[0])
            module_name: str = module_name_no_extensions

        commands: list = [
                config.get("compiler").cpp_compiler,
                '--std=c++' + config.get("language").cpp_standard,
                '-stdlib=' + config.get("language").std_lib,
                '-fmodules',
                '--precompile',
                '-o', f'{module_ifcs_dir_path}/{module_name}.pcm',
                module
            ]
        if not module.__contains__(".cppm"):
            commands.append('-Xclang')
            commands.append('-emit-module-interface')

        subprocess.Popen(commands).wait()

    if verbose:
        print('...\nPrecompilation finished!')

    return module_ifcs_dir_path, module_ifcs


def _compile_module_implementations(
    config: dict,
    verbose: bool,
    project_name: str
):
    """
        Compiles the module implementation units, when the declaration
        it's splitted from the implementation, usually in interface file
        and implementation file.

        This process needs to know about the prebuild module interface
        units, and point the implementation unit to the correct
        module interface file.
    """
    if verbose:
        print('Compiling the module implementations...')

    commands: list = [
        config.get('compiler').cpp_compiler,
        '--std=c++' + config.get('language').cpp_standard,
        '-stdlib=' + config.get('language').std_lib,
        '-Xclang',
        '-emit-module-interface',
    ]

    mods_from_config: list = config.get('modules').implementations
    module_impls: list = [] if len(mods_from_config) == 1 \
        else mods_from_config

    ifcs_path = f'./{project_name}/include/{project_name}/*.cppm'
    if len(mods_from_config) == 1:
        for wildcarded_source in glob.glob(ifcs_path):
            module_impls.append(wildcarded_source)

    print(f'MODULES IMPL: {module_impls}')

    for module_impl in module_impls:
        # Generates the path for the special '**' Zork syntax
        commands.append(module_impl.replace('\\', '/'))
        commands.append('-o')
        mod = module_impl \
                .replace('\\', '/') \
                .split('/') \

        mod2 = mod[(len(mod) - 1)][0]
        commands.append(mod2 + '.pcm')

    print(f'COMMANDS: ...\n {commands}')
    subprocess.Popen(commands).wait()

    if verbose:
        print('...\nMIU Precompilation finished!')


def generate_build_output_directory(config: dict):
    """ Creates the directory where the compiler will dump the
        generated files after the build process """
    output_build_dir = config['build'].output_dir
    if not output_build_dir.strip('./') in os.listdir():
        subprocess.Popen(['mkdir', output_build_dir]).wait()
