pub const DEFAULT_DIRECTORY: &str="example";
pub const DEFAULT_CONFIG_NAME: &str = "zork.conf";

pub const INTERFACE_MOD_FILE: &str = "
export module math;
export namespace math {
    int sum(int num1, int num2);
    int multiply(int num1, int num2);
    int substract(int num1, int num2);
    int divide(int num1, int num2);
}
";

pub const SRC_MOD_FILE: &str = "
module math;
// Implementation of the definitions on the module unit interface
// for the sum and multiply math operations
namespace math {
    int sum(int num1, int num2) {
        return num1 + num2;
    }
    int multiply(int num1, int num2) {
        return num1 * num2;
    }
}
";

pub const SRC_MOD_FILE_2: &str = "
module math;
// Implementation of the definitions on the module unit interface
// for the substract and divide math operations
namespace math {
    int substract(int num1, int num2) {
        return num1 - num2;
    }
    int divide(int num1, int num2) {
        return num1 / num2;
    }
}
";

pub const MAIN: &str = r#"
import std;
import math;
int main() {
    std::cout << "Hello from an autogenerated Zork project!" << std::endl;
    std::cout << "RESULT '+': " << math::sum(2, 8) << std::endl;
    std::cout << "RESULT '-': " << math::substract(8, 2) << std::endl;
    std::cout << "RESULT '*': " << math::multiply(2, 8) << std::endl;
    std::cout << "RESULT '/': " << math::divide(2, 2) << std::endl;
    return 0;
}
"#;

pub const ZORK_CONF: &str = r#"
#This file it's autogenerated as an example of a Zork config file
[project]
name = "calculator"
authors = [ "Zero Day Code" ]  # Replace this for the real authors
[compiler]
cpp_compiler = "clang"
cpp_standard = "20"
std_lib = "libcpp"
[build]
output_dir = "./out"
[executable]
executable_name = "<autogenerated_executable>"
sources = [
    "*.cpp"
]
auto_execute = true
[tests]
tests_executable_name = "zork_proj_tests"
sources = [
    "*.cpp"
]
auto_run_tests = true
[modules]
base_ifcs_dir = "<project_name>/ifc/"
interfaces = [ "*.cppm" ]
base_impls_dir = "<project_name>/src/"
implementations = [
    "math.cpp",
    "math2.cpp=[math]"
]
"#;
