import platform


""" Constant definitions across the whole program """
PROJECT_VERSION: str = '0.3.0'
CONFIGURATION_FILE_NAME: str = 'zork.conf'

""" Retrieves the OS available info """
OS = platform.system()
OS_release = platform.release()
OS_version = platform.version()  # Unused for the moment
OS_architecture = platform.architecture()[0]
OS_arch_linkage = platform.architecture()[1]


# Content for the autogenerated files

ZORK_CONF_AUTOG: str = \
    """# This file it's autogenerated as an example of a Zork config file

[[#compiler]]
cpp_compiler: clang++

[[#language]]
cpp_standard: 20
std_lib: libc++
modules: <autog_test>/src/<autog_test>/*.cppm

[[#build]]
output_dir: ./out

[[#executable]]
executable_name: <autogenerated_executable>
sources: *.cpp
auto_execute: true
    """

MAIN_CPP: str = \
    """#include <iostream>
import math;

int main() {
    std::cout << "Hello from an autogenerated Zork project!" << std::endl;
    std::cout << "RESULT +: " << sum(2, 8) << std::endl;
    std::cout << "RESULT *: " << multiply(2, 8) << std::endl;
    return 0;
}
    """

SRC_MOD_FILE: str = \
    """export module math;

export {
    int sum(int num1, int num2) {
        return num1 + num2;
    }

    int multiply(int num1, int num2) {
        return num1 * num2;
    }
}
    """
