#include <iostream>
import math;

int main() {
    std::cout << "Hello from an autogenerated Zork project!" << std::endl;
    std::cout << "RESULT +: " << sum(2, 8) << std::endl;
    std::cout << "RESULT *: " << multiply(2, 8) << std::endl;
    return 0;
}
    