#include <iostream>
import math;

int main() {
    std::cout << "Hello from an autogenerated Zork project!" << std::endl;

    std::cout << "RESULT '+': " << math::sum(2, 8) << std::endl;
    std::cout << "RESULT '-': " << math::substract(8, 2) << std::endl;
    std::cout << "RESULT '*': " << math::multiply(2, 8) << std::endl;
    std::cout << "RESULT '/': " << math::divide(2, 2) << std::endl;

    return 0;
}
    