const char* compiler = 
#ifdef __clang__
    "Clang";
    import std;
#elif defined(__GNUC__)
    "GCC"
    import <iostream>;
#elif defined(_MSC_VER)
    "MSVC"
    import std.core;
#endif

import math;

int main() {
    std::cout << "\n\nHello from an autogenerated Zork project!" << std::endl;
    std::cout << "The program is running with: " << compiler << std::endl << std::endl;
    std::cout << "RESULT '+': " << math::sum(2, 8) << std::endl;
    std::cout << "RESULT '-': " << math::substract(8, 2) << std::endl;
    std::cout << "RESULT '*': " << math::multiply(2, 8) << std::endl;
    std::cout << "RESULT '/': " << math::divide(2, 2) << std::endl;
    return 0;
}
