
const char* compiler =
#if defined(__clang__)
    "Clang";
    import std;
#elif (defined(__GNUC__) || defined(__GNUG__)) && !defined(__clang__)
    "GCC";
    import <iostream>;
#elif defined
    "MSVC";
    import std.core;
#endif

import math;
import partitions;

int main() {
    std::cout << "\nHello from an autogenerated Zork project!" << std::endl;
    std::cout << "The program is running with: " << compiler << std::endl << std::endl;
    std::cout << "RESULT '+': " << math::sum(2, 8) << std::endl;
    std::cout << "RESULT '-': " << math::substract(8, 2) << std::endl;
    std::cout << "RESULT '*': " << math::multiply(2, 8) << std::endl;
    std::cout << "RESULT '/': " << math::divide(2, 2) << std::endl << std::endl;

    std::cout << "Testing interface module partitions, by just returning a 42: " 
        << just_a_42() << std::endl;
    return 0;
}
