const char* compiler =
#if defined(__clang__)
    "Clang";
    import std;
#elif (defined(__GNUC__) || defined(__GNUG__)) && !defined(__clang__)
    "GCC";
    import <iostream>;
#elif defined(_MSC_VER)
    "MSVC";
    import std;
    import std.compat;
#endif

import math;

int main() {
    std::cout << "\nHello from an autogenerated Zork project!" << std::endl;
    std::cout << "The program is running with: " << compiler << std::endl << std::endl;
    std::cout << "RESULT of 2 + 8 = " << math::sum(2, 8) << std::endl;
    std::cout << "RESULT of 8 - 2 = " << math::subtract(8, 2) << std::endl;
    std::cout << "RESULT of 2 * 8 = " << math::multiply(2, 8) << std::endl;
    std::cout << "RESULT of 2 / 2 = " << math::divide(2, 2) << std::endl << std::endl;

    #if defined(_MSC_VER)
        printf("Import std.compat to get global names like printf()\n");
    #endif

    return 0;
}
