//! The filenames for the autogenerated C++ example with the command `new`

pub const IFC_PART_FILE: &str = include_str!("partitions.cppm");
pub const IFC_PART_PARTITION_FILE: &str = include_str!("interface_partition.cppm");
pub const PARTITIONS_INTERNAL_PARTITION_FILE: &str = include_str!("internal_partition.cpp");
pub const IFC_MOD_FILE: &str = include_str!("math.cppm");
pub const SRC_MOD_FILE: &str = include_str!("math.cpp");
pub const SRC_MOD_FILE_2: &str = include_str!("math2.cpp");
pub const MAIN: &str = include_str!("main.cpp");
pub const MAIN_BASIC: &str = include_str!("main_basic.cpp");

pub const CONFIG_FILE: &str = include_str!("zork_example.toml");
pub const CONFIG_FILE_MSVC: &str = include_str!("zork_example_msvc.toml");
pub const CONFIG_FILE_BASIC: &str = include_str!("zork_example_basic.toml");
pub const CONFIG_FILE_BASIC_MSVC: &str = include_str!("zork_example_basic_msvc.toml");

pub const STD_HEADER: &str = include_str!("std.h");
pub const ZORK_MODULEMAP: &str = include_str!("zork.modulemap");
