///! The filenames for the autogenerated C++ example with the command `new`

pub const IFC_MOD_FILE: &str = include_str!("math.cppm");
pub const SRC_MOD_FILE: &str = include_str!("math.cpp");
pub const SRC_MOD_FILE_2: &str = include_str!("math2.cpp");
pub const MAIN: &str = include_str!("main.cpp");
pub const CONFIG_FILE: &str = include_str!("zork_example.toml");
pub const STD_HEADER: &str = include_str!("std.h");
pub const ZORK_MODULEMAP: &str = include_str!("zork.modulemap");
