name: Pylint

on: 
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --rcfile=.pylintrc
