name: MSVC Tests For Windows builds

on:
  push:
    branches: 'main'
  pull_request:
    branches: '*'

jobs:
  tests:
    name: Run the tests - MSVC
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Caching project dependencies
        id: project-cache
        uses: Swatinem/rust-cache@v2

      - name: Setting up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Running the tests for the project
        run: |
          cd zork++
          cargo test 2>&1 msvc --color=always --no-fail-fast -- --nocapture --show-output --test-threads=1
